# Generated by Django 5.2.16 on 2026-07-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='ReportImageModel',
        ),
    ]
