# Generated by Django 5.2.16 on 2026-07-29 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_remove_reportmodel_author_delete_reportimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
